apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: HEAD
    chart: argo-cd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

