apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
    # annotations:
    #service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
      #service.beta.kubernetes.io/aws-load-balancer-type: external
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: NodePort
  selector:
    role: frontend
